vanus-labs/docs

- user-manual/how-to/managing-subscription.md
Signed-off-by: delu <delu.xu@linkall.com>
> docs: add manag subscription doc

- user-manual/getting-started.md
- user-manual/introduction/what-is-vanus.md
> docs: add getting-started

- user-manual/connectors/source/s3.md
> docs: add source-s3 doc

- user-manual/connectors/sink/mangodb.md
- user-manual/connectors/sink/s3.md
- user-manual/connectors/source/s3.md
- user-manual/connectors/source/sns.md
- user-manual/connectors/source/sqs.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
> Docs: modify the connector title to be more uniformed

- user-manual/getting-started/quick-start.md
- user-manual/how-to/consuming/using-sdk.md
- zh/user-manual/how-to/consume-events/using-sdk.md
1. https://github.com/linkall-labs/vanus/pull/273
> docs: update according to v0.4

- user-manual/connectors/source/mysql.md
> docs: fix typos in mysql source.

- docusaurus.config.js
> feat: add the Plausible Analytics snippet for docs

- user-manual/getting-started/installation.md
- user-manual/getting-started/quick-start.md
update vanus version to v0.4.0
> docs: update vanus version to v0.4.0

- sidebars.js
- user-manual/connectors/sink/mysql.md
- user-manual/connectors/sink/s3.md
- user-manual/connectors/source/github.md
- user-manual/connectors/source/http.md
- user-manual/connectors/source/mysql.md
- user-manual/connectors/source/s3.md
- user-manual/connectors/source/sns.md
- user-manual/connectors/source/sqs.md
- added GitHub Source
- added HTTP Source
- fix typos
> Docs: added Source github and http. fixed typos

- user-manual/getting-started/quick-start.md
> docs: fix quick-start create subscription sink 

- user-manual/how-to/use-gcloud-functions.md
- user-manual/how-to/use-lambda.md
Signed-off-by: delu <delu.xu@linkall.com>
> docs: add how to use lambda and gcloud functions doc

- user-manual/connectors.md
- user-manual/connectors/sink.md
- user-manual/connectors/source.md
> update Connector content

- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/issue-report.md
- .github/ISSUE_TEMPLATE/question.md
Add issue template for Vanus documentation.
> docs: add issue templates

- docusaurus.config.js
> chore: update GitHub repo link

- content/introduction/what-is-vanus.md
> docs: remove opensource notice

- content/how-to/consume/using-sdk.md
> docs: update consumer doc

- content/connectors/source/kafka.md
Added Kafka source readme to docs
> docs: add kafka source to docs

- content/connectors/sink/display.md
> docs: Add display sink

- content/getting-started.md
- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
- content/how-to/consume/using-sdk.md
- content/how-to/manage-eventbus.md
- content/how-to/manage-subscription.md
Solving Issue: N/a
updating due to vanus v0.5 released
> docs: updating due to vanus v0.5 released

- event/Vanus-Survey.md
Add event dir and Vanus survey event.
> docs: add survey event

- event/Vanus-Survey.md
> docs: fix wrong markdown header

- content/introduction/architecture.md
- content/introduction/concepts.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
Solving Issue: #102
Modified Vance in the docs architecture and concept.
> docs: resolved issue #102

- event/Vanus-Survey.md
> docs: close survey event

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
> docs: update to v0.5.1

- content/getting-started/quick-start.mdx
> docs: add vsctl for mac intel

- CONTRIBUTING.md
> docs: replace CLA with DCO

- content/how-to/manage-subscription/function-reference.md
- content/how-to/manage-subscription/transformer.md
> docs: fix bad links

- src/pages/index.js
[
](docs: remove redundant title)
> docs: remove redundant title

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
Signed-off-by: wenfeng <sxian.wang@gmail.com>
Update Vanus version to v0.5.3
> docs: update vanus version to v0.5.3

- blog/authors.yml
[
](chore: update author info)
> chore: update author info

- content/connectors/source/kafka.md
- sidebars.js
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
> docs: update sidebar

- content/how-to/manage-subscription/transformer.md
> docs: update transformer doc

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/installation.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/quick-start.mdx
Signed-off-by: wenfeng <sxian.wang@gmail.com>
Solving Issue: N/a
update vanus version to v0.5.4
> docs: update vanus version to v0.5.4

- content/getting-started/installation.mdx
Signed-off-by: Ehigiator Akhile <akhileehis@gmail.com>
> docs: Updated Installation Guide

- content/how-to/manage-subscription/function-reference.md
- content/how-to/manage-subscription/function-reference/date-time.md
> docs: modify function date doc

- community/community-events/top-10-active-contributors-2022.md
> top-10-active-contributors.md has been updated

- src/components/HomepageHeader/index.js
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
> docs: fix animation

- content/how-to/vsctl.md
> Updated vstl.md

- sidebars.js
> update document directory

- blog/2023-01-04-event-driven-architecture/index.md
> docs: update blog

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/installation.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/quick-start.mdx
update vanus version to v0.5.7
> docs: update vanus version to v0.5.7

- content/introduction/concepts.md
Solving Issue: #222 
Rewrite the concept of transformer in the documentation and briefly explain the idea of Define, Function, and template.
> Update concepts.md file

- content/getting-started/quick-start.mdx
using all-in-one container in quick-start instead of minikube
> docs: using all-in-one container to replace minikube in quickstart

- content/introduction/concepts.md
> docs: Update Transformer concept

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
> docs: update quickstart to v0.6.0

- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
- content/how-to/manage-subscription.md
- content/how-to/manage-subscription/filters.md
- content/how-to/manage-subscription/transformer.md
- content/how-to/produce/using-sdk.md
- content/how-to/use-gcloud-functions.md
- content/how-to/use-lambda.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/quick-start.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/manage-subscription.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/use-gcloud-functions.md
- i18n/zh-CN/docusaurus-plugin-content-docs/current/how-to/use-lambda.md
add --name for subscription creation
> fix: add --name for subscription creation

- content/connectors/sink.md
- content/connectors/source.md
> docs: fix list connector

- blog/2023-02-04-mysql-slack-blog/index.md
- Update target port to "30002"
> docs: refractor mysql

- blog/2023-02-05-github-slack/index.md
> Update: Build a notification system that pushes any GitHub event to Slack in 5 minutes.

- blog/2023-02-05-github-slack/index.md
> update: github to slack

- blog/2023-02-05-github-slack/index.md
> blog: github to slack,update confilg.yml

- blog/2023-02-05-github-slack/index.md
> add playground

- docusaurus.config.js
> fix: fix logo jump back to main website

- docusaurus.config.js
> style: update plausible domain

- content/introduction/use-cases.md
- sidebars.js
> docs: add use cases

- blog/2023-01-30-awsbilling-slack-blog/index.md
- blog/2023-02-04-mysql-slack-blog/index.md
- blog/2023-02-05-github-slack/index.md
- blog/2023-02-05-s3-slack-blog/index.md
- blog/2023-02-07-send-email-notification-on-AWS-S3-events/index.md
- blog/2023-02-09-http-s3-blog/index.md
- blog/2023-02-19-mysql-email-blog/index.md
- blog/2023-02-22-mysql-s3-blog/index.md
- blog/2023-03-24-mysql-http/index.md
- content/getting-started/installation.mdx
- content/getting-started/quick-start.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/installation.mdx
- i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/quick-start.mdx
change download.linkall.com to dl.vanus.ai
> docs: change download.linkall.com to dl.vanus.ai

- content/vanus-open-source/quick-start.mdx
> docs: update vanus to v0.7.0

- src/pages/index.js
> docs: update home

- src/css/custom.scss
fix: move code copy button to the top right corner
@yuanmoon Please review it
> fix: move code copy button to the top right corner

- content/how-to/manage-subscription/filters.md
> docs: modify filter doc

- content/how-to/manage-subscription/transformer.md
> docs: modify transformer doc

- content/connectors/source.md
> fix: docs link error

- content/how-to/manage-subscription/function-reference.md
> updated list of functions

- content/maintain/upgrade/using-vanus-operator.md
- content/maintain/upgrade/using-vsctl.md
> feat: add cluster upgrade docs

- content/how-to/manage-subscription/function-reference.md
- content/how-to/manage-subscription/function-reference/array.md
- content/how-to/manage-subscription/function-reference/string.md
- content/how-to/manage-subscription/function-reference/structure.md
> Update strings, struct and array functions

- content/cloud-docs/sink/aws-rds-mysql/setup.md
- content/cloud-docs/sink/elasticsearch/setup.md
- content/cloud-docs/sink/mongodb/setup.md
- content/cloud-docs/source/aws-eventbridge/setup.md
- content/cloud-docs/source/aws-mysql/setup.md
- content/cloud-docs/source/aws-postgresql-cdc/setup.md
- content/cloud-docs/source/chatai/setup.md
- content/cloud-docs/source/mongodb/setup.md
- content/cloud-docs/source/slack/setup.md
- content/cloud-docs/source/webhook/setup.md
> changed heading type

- content/cloud-docs/source/auth0/setup.md
- content/cloud-docs/source/aws-billing/setup.md
- content/cloud-docs/source/aws-eventbridge/setup.md
- content/cloud-docs/source/aws-s3/setup.md
- content/cloud-docs/source/chatai/setup.md
- content/cloud-docs/source/chatgpt/setup.md
- content/cloud-docs/source/cloudevents/setup.md
- content/cloud-docs/source/grafana/setup.md
- content/cloud-docs/source/labeling/setup.md
- content/cloud-docs/source/schedule/setup.mdx
- content/cloud-docs/source/shopify-webhook/setup.md
- content/cloud-docs/source/slack/setup.md
- content/cloud-docs/source/stripe/setup.md
- content/cloud-docs/source/webhook/setup.md
- content/user-guides/connector-guides/source/slack/webhook.md
> docs: update Cloud docs

- content/cloud-docs/source/aws-s3/setup.md
> docs: update s3 titles 

- content/cloud-docs/source/postgres/setup.md
> docs: Vanus Cloud update

- content/getting-started/Vanus-ai.md
- content/getting-started/what-is-vanus.md
- content/vanus-ai/features.md
- content/vanus-ai/use-cases.md
- content/vanus-ai/what-is-vanus-ai.md
- content/vanus-os/what-is-vanus-os.md
> docs: update and review of new documents

- content/vanus-ai/how-to/create-AI.md
- content/vanus-connect/what-is-vanus-connect.md
- sidebars.js
> docs: update name of Ai tutorial

- content/vanus-connect/template-guides/auth0-login-discord.md
- content/vanus-connect/template-guides/auth0-login-slack.md
- content/vanus-connect/template-guides/aws-billing-to-google-sheet.md
- content/vanus-connect/template-guides/aws-bucket-discord.md
- content/vanus-connect/template-guides/github-comment-discord.md
- content/vanus-connect/template-guides/github-developer-360.md
- content/vanus-connect/template-guides/github-issue-created-feishu.mdx
- content/vanus-connect/template-guides/github-issue-discord.md
- content/vanus-connect/template-guides/github-merge-pr-discord.md
- content/vanus-connect/template-guides/github-merge-pr-slack.md
- content/vanus-connect/template-guides/github-open-pr-discord.md
- content/vanus-connect/template-guides/github-open-pr-feishu.md
- content/vanus-connect/template-guides/github-pull-request-opened-slack.mdx
- content/vanus-connect/template-guides/github-star-discord.md
- content/vanus-connect/template-guides/github-star-triggers-slack.md
- content/vanus-connect/template-guides/github-starred-feishu.md
- content/vanus-connect/template-guides/grafana-discord.md
- content/vanus-connect/template-guides/grafana-slack.md
- content/vanus-connect/template-guides/s3-bucket-slack.md
- content/vanus-connect/template-guides/s3-object.discord.md
- content/vanus-connect/user-guides/get-webhook-url.md
…then ran it through Grammarly for certainty.
It fixes grammatical errors in the template guide section of the Vanus Connect docs.
> Read through template guide section of the docs to check for errors

- content/vanus-ai/how-to/Vanus-AI-API-cn.md
- content/vanus-ai/how-to/Vanus-AI-API-en.md
> fix: update vanus ai docs

- content/vanus-ai/how-to/Vanus-AI-API-cn.md
- content/vanus-ai/how-to/Vanus-AI-API-en.md
- content/vanus-ai/how-to/api.md
> fix: update vanus ai api docs

- content/vanus-connect/connector-guides/sink/aws-rds-mysql/setup.md
- content/vanus-connect/connector-guides/sink/aws-s3/setup.md
> Update Vanus Connect Docs

- content/vanus-connect/connector-guides/source/auth0/setup.md
- content/vanus-connect/connector-guides/source/javascript/setup.md
- content/vanus-connect/connector-guides/source/jenkins/setup.md
- content/vanus-connect/connector-guides/source/zoho-crm/setup.md
> Sidebar Fix

- content/vanus-connect/connector-guides/source/javascript/setup.md
- content/vanus-connect/connector-guides/source/jenkins/setup.md
- content/vanus-connect/connector-guides/source/mongodb/setup.md
- content/vanus-connect/connector-guides/source/zoho-crm/setup.md
Adds introductory content for 3 source connector docs, namely: Javascript, Jenkins and Zoho CRM
> Missing introduction for javascript, jenkins and zohocrm

- content/vanus-ai/how-to/Vanus-AI-API-en.md
- content/vanus-ai/how-to/api.md
> Update Vanus AI API docs

- content/vanus-ai/how-to/Vanus-AI-Embed-cn.md
> update web widget doc

- content/cloud-docs/sink/whatsapp/setup.mdx
- content/vanus-connect/connector-guides/sink/whatsapp/setup.mdx
- content/vanus-os/connectors/sink/sink-slack/README.md
- content/vanus-os/connectors/source/source-alicloud-billing/README.md
- content/vanus-os/connectors/source/source-aws-billing/README.md
- content/vanus-os/connectors/source/source-aws-s3/README.md
- content/vanus-os/connectors/source/source-aws-sns/README.md
- content/vanus-os/connectors/source/source-aws-sqs/README.md
- content/vanus-os/connectors/source/source-github/README.md
- content/vanus-os/connectors/source/source-http/README.md
- content/vanus-os/connectors/source/source-kafka/README.md
- content/vanus-os/connectors/source/source-mongodb/README.md
- content/vanus-os/connectors/source/source-mysql/README.md
- content/vanus-os/connectors/source/source-postgres/README.md
> docs: update WhatsApp

- content/cloud-docs/sink/whatsapp/setup.mdx
- content/vanus-connect/connector-guides/sink/whatsapp/setup.mdx
> Docs: Update WhatsApp Sink Connector Docs

- content/cloud-docs/sink/whatsapp/setup.mdx
> docs: Whatsapp 

- content/vanus-os/quick-start.mdx
> Docs: Update Vanus OS Docs

- content/cloud-docs/sink/whatsapp/setup.md
> docs: WhatsApp Update

- content/cloud-docs/source/test-connector/setup.md
- content/vanus-ai/integrations/discord.md
- content/vanus-ai/integrations/whatsapp.md
> docs: Add Integrations 

- content/cloud-docs/sink/feishu/setup.md
- content/vanus-ai/integrations/whatsapp.md
> Docs: updates

- content/vanus-connect/connector-guides/source/shopify-webhook/setup.md
> Docs: Update Shopify Webhook Source Connector

- content/vanus-ai/integrations/discord/index.md
> docs: Update discord.

- content/vanus-os/installation.md
- content/vanus-os/quick-start.mdx
> Docs: Update Vanus OS

- content/vanus-ai/beginning/app-settings/app-settings.md
- content/vanus-ai/how-to/website-embedding.md
- content/vanus-ai/integrations/dingtalk/index.md
- content/vanus-ai/integrations/discord/index.md
- content/vanus-ai/integrations/feishu/feishu.md
- content/vanus-ai/integrations/slack/index.md
- content/vanus-ai/integrations/whatsapp/index.md
> Docs: Added links to necessary docs

- content/cloud-docs/sink/mysql/setup.md
- content/vanus-connect/connector-guides/sink/mysql/setup.md
> Docs: Sink-MYSQL

- content/cloud-docs/sink/mysql/setup.md
- content/vanus-connect/connector-guides/sink/mysql/setup.md
> Docs: Mysql-sink

- content/vanus-ai/how-to/Vanus-AI-API-en.md
> fix: update api docs to add model

- sidebars.js
> remove sidebar content

- content/vanus-connect/connector-guides/sink/aws-s3/setup.md
- content/vanus-connect/connector-guides/source/aws-mysql/setup.md
- content/vanus-connect/connector-guides/source/aws-postgresql-cdc/setup.md
> Update amazon connector titles.

- content/vanus-ai/integrations/slack/index.md
> Docs: AI Slack Integration Fix

- content/vanus-ai/integrations/feishu/feishu.md
> Docs: AI Feishu Integration Fix

- content/cloud-docs/source/aws-billing/setup.md
- content/cloud-docs/source/aws-s3/setup.md
- content/cloud-docs/source/aws-sqs/setup.md
- content/cloud-docs/source/webhook/setup.md
- content/vanus-connect/connector-guides/source/aws-billing/setup.md
- content/vanus-connect/connector-guides/source/aws-s3/setup.md
- content/vanus-connect/connector-guides/source/aws-sqs/setup.md
- content/vanus-connect/connector-guides/source/webhook/setup.md
> Docs: Fixes suggested after checking docs

- content/cloud-docs/source/shopify-webhook/setup.md
- content/vanus-connect/connector-guides/source/shopify-webhook/setup.md
> Docs: Update Shopify Webhook Source

- content/cloud-docs/source/shopify-webhook/setup.md
> Docs: update shopify webhook

- content/cloud-docs/source/stripe/setup.md
> docs stripe source
